// File generated by scripts/import_bradesco_map.js
export const teatroBradescoManifest = {
  "venueId": "teatro-bradesco",
  "hallName": "Teatro Bradesco",
  "stageLabel": "Palco",
  "geometryPath": "/maps/teatro-bradesco-geometry.json",
  "backgroundAssetPath": "/seatmaps/teatro-bradesco-background.svg",
  "variant": "theater",
  "viewport": {
    "width": 1311,
    "height": 994
  },
  "totalSeats": 439,
  "availableSeats": 55,
  "notes": [
    "Mapa do Teatro Bradesco importado da fonte operacional (Sympla Bileto).",
    "Geometria normalizada da fonte para o dom&iacute;nio local.",
    "Background separado em camada visual est&aacute;tica."
  ],
  "sectionStats": {
    "plateia-vip": {
      "total": 439,
      "selectable": 55
    }
  },
  "sections": [
    {
      "id": "frisa-plateia-superior",
      "name": "FRISA PLATEIA SUPERIOR",
      "shortLabel": "FRISA PLAT",
      "price": 150,
      "tone": "slate"
    },
    {
      "id": "balcao-a",
      "name": "BALCAO A",
      "shortLabel": "BALCAO A",
      "price": 150,
      "tone": "slate"
    },
    {
      "id": "complemento",
      "name": "COMPLEMENTO",
      "shortLabel": "COMPLEMENT",
      "price": 150,
      "tone": "slate"
    },
    {
      "id": "plateia-superior",
      "name": "PLATEIA SUPERIOR",
      "shortLabel": "PLATEIA SU",
      "price": 150,
      "tone": "slate"
    },
    {
      "id": "balcao-b",
      "name": "BALCAO B",
      "shortLabel": "BALCAO B",
      "price": 150,
      "tone": "slate"
    },
    {
      "id": "frisa-balcao",
      "name": "FRISA BALCAO",
      "shortLabel": "FRISA BALC",
      "price": 150,
      "tone": "slate"
    },
    {
      "id": "plateia-vip",
      "name": "PLATEIA VIP",
      "shortLabel": "PLATEIA VI",
      "price": 150,
      "tone": "slate"
    }
  ]
} as const;
